
INSERT INTO Types (Type, Kind) VALUES ('BUILDING_BOROBUDUR', 'KIND_BUILDING');

INSERT INTO Buildings (BuildingType, Name, Description, PrereqCivic, Cost, AdvisorType, MaxWorldInstances, IsWonder, RequiresPlacement, Quote)
VALUES ('BUILDING_BOROBUDUR', 'LOC_BUILDING_BOROBUDUR_NAME', 'LOC_BUILDING_BOROBUDUR_DESCRIPTION', 'CIVIC_NAVAL_TRADITION', 710, 'ADVISOR_CULTURE', '1', 1, 1, 'LOC_BUILDING_BOROBUDUR_QUOTE');

